name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out repo
    - name: Check out repo
      uses: actions/checkout@v2

    # Step 2: Install Azure ML extension
    - name: Install az ml extension
      run: az extension add -n ml -y

    # Step 3: Azure login using service principal
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 4: Trigger the Azure ML job
    - name: Trigger Azure ML job
      run: |
        az ml job create --file ./Users/MAyinde/src/model/job.yaml --resource-group latemlopRG --workspace-name mlopworkspace
